# Generated by Django 3.2.9 on 2022-06-20 05:20

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_wine_gin_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wine',
            name='gin_idx',
        ),
        migrations.AddIndex(
            model_name='wine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['variety'], name='variety_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['winery'], name='winery_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='description_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
