# Generated by Django 3.2.9 on 2022-06-22 15:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20220620_0520'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wine',
            name='variety_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='wine',
            name='winery_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='wine',
            name='description_gin_idx',
        ),
        migrations.AddField(
            model_name='wine',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_index'),
        ),
    ]
