repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: cd server && poetry run isort --profile black .
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: cd server && poetry run black .
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: cd server && poetry run flake8 .
        types: [python]
